### ISSUE TITLE
Conversion Algorithm

### ISSUE THREAD

**Issue by jordan-wirth** [redoverture/image_to_ascii#3]
This algorithm needs to map image pixels to ASCII characters, preferably quickly.
It can assume a pre-processed image with intensity values as floating point numbers 0.0 - 1.0.

**Comment by Zippoman924** [comment]
**Copied from Old Ticket**

We will need a list of ASCII characters, sorted by intensity values.
These may or may not need to be associated with a list of ranges which they can map to for the image.
