### ISSUE TITLE
Image Pre-Processing Enhancement

### ISSUE THREAD

**Issue by jordan-wirth** [redoverture/image_to_ascii#5]
In order to effectively convert an image to ASCII, we will need to apply some pre-processing algorithms to enhance the image.

We'll need to research sharpening and edge detection algorithms, as well as some that might help us redistribute images which might have low contrast (which would be difficult to convert to ASCII, without losing all the detail.)

**Comment by Zippoman924** [comment]
### Things to Add

* Edge Detection
* Histogram Equalization for contrast issues

**Comment by Zippoman924** [comment]
I was able to put in edge detection into another file. It looks like for the `histeq()` we will either need to add that into some of the UI code somewhere and idk how to do that or we can just add it into the conversion algorithm at the start. We can discuss this later today.
